### ISSUE TITLE
Can't find miRmap function

### ISSUE THREAD

**Issue by klconnor11** [Jon-Simpson/miRmapper#1]
Hi, 

Love the sound of this package. 

After loading miRmapper I was trying to use your miRmap function as below. 

miRmap(interaction.file = "data/up_mirs.csv", DEgenes.file = "data/down_genes.csv")

However the miRmap function did not seem to exist and I couldn't get the function to run using miRmapper. 

Your help with this would be great!

Thanks
Katie

**Comment by Jon-Simpson** [comment]
Hi,

Sorry for the delayed response. The Getting Started documentation was a bit out of date, I've corrected it. There is no longer a miRmap function, but is rather initialized with `miRmapper(interactions=interact, DEgenes=de_genes)` instead.
